version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: prueba
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data